// This file is autogenerated by the JUCE BrowserIntegrationPluginClient class,
// by inspecting all the parameters in the AudioProcessorValueTreeState.
//
// It is updated whenever you run the app in debug mode with the macro
// BROWSER_INTEGRATION_WRITE_PARAMETER_CONFIG_IN_DEBUG=1.
//
// You shouldn't need to edit this manually - if you add a new parameter,
// running the app in debug mode should be enough to update this.
        
import { ParameterModel } from "../../juceIntegration/models/ParameterModel";

export type ParametersType = {
  delayFeedback: ParameterModel<number>;
  delayTime: ParameterModel<number>;
  effectOrder: ParameterModel<"Filter - Pitch shift" | "Pitch shift - Filter">;
  filterHighGain: ParameterModel<number>;
  filterLowGain: ParameterModel<number>;
  filterMidGain: ParameterModel<number>;
  latentsOffset: ParameterModel<number>;
  latentsScale: ParameterModel<number>;
  lfo1BeatSync: ParameterModel<boolean>;
  lfo1BeatSyncRate: ParameterModel<"4 Bars" | "2 Bars" | "1 Bar" | "1 Bar Dotted" | "1 Bar Triplet" | "1/2 Bar" | "1/2 Bar Dotted" | "1/2 Bar Triplet" | "1 Beat" | "1 Beat Dotted" | "1 Beat Triplet" | "1/2 Beat" | "1/2 Beat Dotted" | "1/2 Beat Triplet" | "1/4 Beat" | "1/4 Beat Dotted" | "1/4 Beat Triplet" | "1/8 Beat" | "1/8 Beat Dotted" | "1/8 Beat Triplet" | "1/16 Beat" | "1/16 Beat Dotted" | "1/16 Beat Triplet" | "1/32 Beat" | "1/32 Beat Dotted" | "1/32 Beat Triplet" | "1/64 Beat">;
  lfo1Enabled: ParameterModel<boolean>;
  lfo1Offset: ParameterModel<number>;
  lfo1Phase: ParameterModel<number>;
  lfo1PulseWidth: ParameterModel<number>;
  lfo1Rate: ParameterModel<number>;
  lfo1Scale: ParameterModel<number>;
  lfo1Type: ParameterModel<"Sine" | "Triangle" | "Ramp" | "Square" | "Noise">;
  lfo2BeatSync: ParameterModel<boolean>;
  lfo2BeatSyncRate: ParameterModel<"4 Bars" | "2 Bars" | "1 Bar" | "1 Bar Dotted" | "1 Bar Triplet" | "1/2 Bar" | "1/2 Bar Dotted" | "1/2 Bar Triplet" | "1 Beat" | "1 Beat Dotted" | "1 Beat Triplet" | "1/2 Beat" | "1/2 Beat Dotted" | "1/2 Beat Triplet" | "1/4 Beat" | "1/4 Beat Dotted" | "1/4 Beat Triplet" | "1/8 Beat" | "1/8 Beat Dotted" | "1/8 Beat Triplet" | "1/16 Beat" | "1/16 Beat Dotted" | "1/16 Beat Triplet" | "1/32 Beat" | "1/32 Beat Dotted" | "1/32 Beat Triplet" | "1/64 Beat">;
  lfo2Enabled: ParameterModel<boolean>;
  lfo2Offset: ParameterModel<number>;
  lfo2Phase: ParameterModel<number>;
  lfo2PulseWidth: ParameterModel<number>;
  lfo2Rate: ParameterModel<number>;
  lfo2Scale: ParameterModel<number>;
  lfo2Type: ParameterModel<"Sine" | "Triangle" | "Ramp" | "Square" | "Noise">;
  lfo3BeatSync: ParameterModel<boolean>;
  lfo3BeatSyncRate: ParameterModel<"4 Bars" | "2 Bars" | "1 Bar" | "1 Bar Dotted" | "1 Bar Triplet" | "1/2 Bar" | "1/2 Bar Dotted" | "1/2 Bar Triplet" | "1 Beat" | "1 Beat Dotted" | "1 Beat Triplet" | "1/2 Beat" | "1/2 Beat Dotted" | "1/2 Beat Triplet" | "1/4 Beat" | "1/4 Beat Dotted" | "1/4 Beat Triplet" | "1/8 Beat" | "1/8 Beat Dotted" | "1/8 Beat Triplet" | "1/16 Beat" | "1/16 Beat Dotted" | "1/16 Beat Triplet" | "1/32 Beat" | "1/32 Beat Dotted" | "1/32 Beat Triplet" | "1/64 Beat">;
  lfo3Enabled: ParameterModel<boolean>;
  lfo3Offset: ParameterModel<number>;
  lfo3Phase: ParameterModel<number>;
  lfo3PulseWidth: ParameterModel<number>;
  lfo3Rate: ParameterModel<number>;
  lfo3Scale: ParameterModel<number>;
  lfo3Type: ParameterModel<"Sine" | "Triangle" | "Ramp" | "Square" | "Noise">;
  lfo4BeatSync: ParameterModel<boolean>;
  lfo4BeatSyncRate: ParameterModel<"4 Bars" | "2 Bars" | "1 Bar" | "1 Bar Dotted" | "1 Bar Triplet" | "1/2 Bar" | "1/2 Bar Dotted" | "1/2 Bar Triplet" | "1 Beat" | "1 Beat Dotted" | "1 Beat Triplet" | "1/2 Beat" | "1/2 Beat Dotted" | "1/2 Beat Triplet" | "1/4 Beat" | "1/4 Beat Dotted" | "1/4 Beat Triplet" | "1/8 Beat" | "1/8 Beat Dotted" | "1/8 Beat Triplet" | "1/16 Beat" | "1/16 Beat Dotted" | "1/16 Beat Triplet" | "1/32 Beat" | "1/32 Beat Dotted" | "1/32 Beat Triplet" | "1/64 Beat">;
  lfo4Enabled: ParameterModel<boolean>;
  lfo4Offset: ParameterModel<number>;
  lfo4Phase: ParameterModel<number>;
  lfo4PulseWidth: ParameterModel<number>;
  lfo4Rate: ParameterModel<number>;
  lfo4Scale: ParameterModel<number>;
  lfo4Type: ParameterModel<"Sine" | "Triangle" | "Ramp" | "Square" | "Noise">;
  lfo5BeatSync: ParameterModel<boolean>;
  lfo5BeatSyncRate: ParameterModel<"4 Bars" | "2 Bars" | "1 Bar" | "1 Bar Dotted" | "1 Bar Triplet" | "1/2 Bar" | "1/2 Bar Dotted" | "1/2 Bar Triplet" | "1 Beat" | "1 Beat Dotted" | "1 Beat Triplet" | "1/2 Beat" | "1/2 Beat Dotted" | "1/2 Beat Triplet" | "1/4 Beat" | "1/4 Beat Dotted" | "1/4 Beat Triplet" | "1/8 Beat" | "1/8 Beat Dotted" | "1/8 Beat Triplet" | "1/16 Beat" | "1/16 Beat Dotted" | "1/16 Beat Triplet" | "1/32 Beat" | "1/32 Beat Dotted" | "1/32 Beat Triplet" | "1/64 Beat">;
  lfo5Enabled: ParameterModel<boolean>;
  lfo5Offset: ParameterModel<number>;
  lfo5Phase: ParameterModel<number>;
  lfo5PulseWidth: ParameterModel<number>;
  lfo5Rate: ParameterModel<number>;
  lfo5Scale: ParameterModel<number>;
  lfo5Type: ParameterModel<"Sine" | "Triangle" | "Ramp" | "Square" | "Noise">;
  modAmount_LFO1_delayFeedback: ParameterModel<number>;
  modAmount_LFO1_delayTime: ParameterModel<number>;
  modAmount_LFO1_filterHighGain: ParameterModel<number>;
  modAmount_LFO1_filterLowGain: ParameterModel<number>;
  modAmount_LFO1_filterMidGain: ParameterModel<number>;
  modAmount_LFO1_latentsOffset: ParameterModel<number>;
  modAmount_LFO1_latentsScale: ParameterModel<number>;
  modAmount_LFO1_lfo1Offset: ParameterModel<number>;
  modAmount_LFO1_lfo1Phase: ParameterModel<number>;
  modAmount_LFO1_lfo1PulseWidth: ParameterModel<number>;
  modAmount_LFO1_lfo1Rate: ParameterModel<number>;
  modAmount_LFO1_lfo1Scale: ParameterModel<number>;
  modAmount_LFO1_lfo2Offset: ParameterModel<number>;
  modAmount_LFO1_lfo2Phase: ParameterModel<number>;
  modAmount_LFO1_lfo2PulseWidth: ParameterModel<number>;
  modAmount_LFO1_lfo2Rate: ParameterModel<number>;
  modAmount_LFO1_lfo2Scale: ParameterModel<number>;
  modAmount_LFO1_lfo3Offset: ParameterModel<number>;
  modAmount_LFO1_lfo3Phase: ParameterModel<number>;
  modAmount_LFO1_lfo3PulseWidth: ParameterModel<number>;
  modAmount_LFO1_lfo3Rate: ParameterModel<number>;
  modAmount_LFO1_lfo3Scale: ParameterModel<number>;
  modAmount_LFO1_lfo4Offset: ParameterModel<number>;
  modAmount_LFO1_lfo4Phase: ParameterModel<number>;
  modAmount_LFO1_lfo4PulseWidth: ParameterModel<number>;
  modAmount_LFO1_lfo4Rate: ParameterModel<number>;
  modAmount_LFO1_lfo4Scale: ParameterModel<number>;
  modAmount_LFO1_lfo5Offset: ParameterModel<number>;
  modAmount_LFO1_lfo5Phase: ParameterModel<number>;
  modAmount_LFO1_lfo5PulseWidth: ParameterModel<number>;
  modAmount_LFO1_lfo5Rate: ParameterModel<number>;
  modAmount_LFO1_lfo5Scale: ParameterModel<number>;
  modAmount_LFO1_outputGain: ParameterModel<number>;
  modAmount_LFO1_pitchOffset: ParameterModel<number>;
  modAmount_LFO2_delayFeedback: ParameterModel<number>;
  modAmount_LFO2_delayTime: ParameterModel<number>;
  modAmount_LFO2_filterHighGain: ParameterModel<number>;
  modAmount_LFO2_filterLowGain: ParameterModel<number>;
  modAmount_LFO2_filterMidGain: ParameterModel<number>;
  modAmount_LFO2_latentsOffset: ParameterModel<number>;
  modAmount_LFO2_latentsScale: ParameterModel<number>;
  modAmount_LFO2_lfo1Offset: ParameterModel<number>;
  modAmount_LFO2_lfo1Phase: ParameterModel<number>;
  modAmount_LFO2_lfo1PulseWidth: ParameterModel<number>;
  modAmount_LFO2_lfo1Rate: ParameterModel<number>;
  modAmount_LFO2_lfo1Scale: ParameterModel<number>;
  modAmount_LFO2_lfo2Offset: ParameterModel<number>;
  modAmount_LFO2_lfo2Phase: ParameterModel<number>;
  modAmount_LFO2_lfo2PulseWidth: ParameterModel<number>;
  modAmount_LFO2_lfo2Rate: ParameterModel<number>;
  modAmount_LFO2_lfo2Scale: ParameterModel<number>;
  modAmount_LFO2_lfo3Offset: ParameterModel<number>;
  modAmount_LFO2_lfo3Phase: ParameterModel<number>;
  modAmount_LFO2_lfo3PulseWidth: ParameterModel<number>;
  modAmount_LFO2_lfo3Rate: ParameterModel<number>;
  modAmount_LFO2_lfo3Scale: ParameterModel<number>;
  modAmount_LFO2_lfo4Offset: ParameterModel<number>;
  modAmount_LFO2_lfo4Phase: ParameterModel<number>;
  modAmount_LFO2_lfo4PulseWidth: ParameterModel<number>;
  modAmount_LFO2_lfo4Rate: ParameterModel<number>;
  modAmount_LFO2_lfo4Scale: ParameterModel<number>;
  modAmount_LFO2_lfo5Offset: ParameterModel<number>;
  modAmount_LFO2_lfo5Phase: ParameterModel<number>;
  modAmount_LFO2_lfo5PulseWidth: ParameterModel<number>;
  modAmount_LFO2_lfo5Rate: ParameterModel<number>;
  modAmount_LFO2_lfo5Scale: ParameterModel<number>;
  modAmount_LFO2_outputGain: ParameterModel<number>;
  modAmount_LFO2_pitchOffset: ParameterModel<number>;
  modAmount_LFO3_delayFeedback: ParameterModel<number>;
  modAmount_LFO3_delayTime: ParameterModel<number>;
  modAmount_LFO3_filterHighGain: ParameterModel<number>;
  modAmount_LFO3_filterLowGain: ParameterModel<number>;
  modAmount_LFO3_filterMidGain: ParameterModel<number>;
  modAmount_LFO3_latentsOffset: ParameterModel<number>;
  modAmount_LFO3_latentsScale: ParameterModel<number>;
  modAmount_LFO3_lfo1Offset: ParameterModel<number>;
  modAmount_LFO3_lfo1Phase: ParameterModel<number>;
  modAmount_LFO3_lfo1PulseWidth: ParameterModel<number>;
  modAmount_LFO3_lfo1Rate: ParameterModel<number>;
  modAmount_LFO3_lfo1Scale: ParameterModel<number>;
  modAmount_LFO3_lfo2Offset: ParameterModel<number>;
  modAmount_LFO3_lfo2Phase: ParameterModel<number>;
  modAmount_LFO3_lfo2PulseWidth: ParameterModel<number>;
  modAmount_LFO3_lfo2Rate: ParameterModel<number>;
  modAmount_LFO3_lfo2Scale: ParameterModel<number>;
  modAmount_LFO3_lfo3Offset: ParameterModel<number>;
  modAmount_LFO3_lfo3Phase: ParameterModel<number>;
  modAmount_LFO3_lfo3PulseWidth: ParameterModel<number>;
  modAmount_LFO3_lfo3Rate: ParameterModel<number>;
  modAmount_LFO3_lfo3Scale: ParameterModel<number>;
  modAmount_LFO3_lfo4Offset: ParameterModel<number>;
  modAmount_LFO3_lfo4Phase: ParameterModel<number>;
  modAmount_LFO3_lfo4PulseWidth: ParameterModel<number>;
  modAmount_LFO3_lfo4Rate: ParameterModel<number>;
  modAmount_LFO3_lfo4Scale: ParameterModel<number>;
  modAmount_LFO3_lfo5Offset: ParameterModel<number>;
  modAmount_LFO3_lfo5Phase: ParameterModel<number>;
  modAmount_LFO3_lfo5PulseWidth: ParameterModel<number>;
  modAmount_LFO3_lfo5Rate: ParameterModel<number>;
  modAmount_LFO3_lfo5Scale: ParameterModel<number>;
  modAmount_LFO3_outputGain: ParameterModel<number>;
  modAmount_LFO3_pitchOffset: ParameterModel<number>;
  modAmount_LFO4_delayFeedback: ParameterModel<number>;
  modAmount_LFO4_delayTime: ParameterModel<number>;
  modAmount_LFO4_filterHighGain: ParameterModel<number>;
  modAmount_LFO4_filterLowGain: ParameterModel<number>;
  modAmount_LFO4_filterMidGain: ParameterModel<number>;
  modAmount_LFO4_latentsOffset: ParameterModel<number>;
  modAmount_LFO4_latentsScale: ParameterModel<number>;
  modAmount_LFO4_lfo1Offset: ParameterModel<number>;
  modAmount_LFO4_lfo1Phase: ParameterModel<number>;
  modAmount_LFO4_lfo1PulseWidth: ParameterModel<number>;
  modAmount_LFO4_lfo1Rate: ParameterModel<number>;
  modAmount_LFO4_lfo1Scale: ParameterModel<number>;
  modAmount_LFO4_lfo2Offset: ParameterModel<number>;
  modAmount_LFO4_lfo2Phase: ParameterModel<number>;
  modAmount_LFO4_lfo2PulseWidth: ParameterModel<number>;
  modAmount_LFO4_lfo2Rate: ParameterModel<number>;
  modAmount_LFO4_lfo2Scale: ParameterModel<number>;
  modAmount_LFO4_lfo3Offset: ParameterModel<number>;
  modAmount_LFO4_lfo3Phase: ParameterModel<number>;
  modAmount_LFO4_lfo3PulseWidth: ParameterModel<number>;
  modAmount_LFO4_lfo3Rate: ParameterModel<number>;
  modAmount_LFO4_lfo3Scale: ParameterModel<number>;
  modAmount_LFO4_lfo4Offset: ParameterModel<number>;
  modAmount_LFO4_lfo4Phase: ParameterModel<number>;
  modAmount_LFO4_lfo4PulseWidth: ParameterModel<number>;
  modAmount_LFO4_lfo4Rate: ParameterModel<number>;
  modAmount_LFO4_lfo4Scale: ParameterModel<number>;
  modAmount_LFO4_lfo5Offset: ParameterModel<number>;
  modAmount_LFO4_lfo5Phase: ParameterModel<number>;
  modAmount_LFO4_lfo5PulseWidth: ParameterModel<number>;
  modAmount_LFO4_lfo5Rate: ParameterModel<number>;
  modAmount_LFO4_lfo5Scale: ParameterModel<number>;
  modAmount_LFO4_outputGain: ParameterModel<number>;
  modAmount_LFO4_pitchOffset: ParameterModel<number>;
  modAmount_LFO5_delayFeedback: ParameterModel<number>;
  modAmount_LFO5_delayTime: ParameterModel<number>;
  modAmount_LFO5_filterHighGain: ParameterModel<number>;
  modAmount_LFO5_filterLowGain: ParameterModel<number>;
  modAmount_LFO5_filterMidGain: ParameterModel<number>;
  modAmount_LFO5_latentsOffset: ParameterModel<number>;
  modAmount_LFO5_latentsScale: ParameterModel<number>;
  modAmount_LFO5_lfo1Offset: ParameterModel<number>;
  modAmount_LFO5_lfo1Phase: ParameterModel<number>;
  modAmount_LFO5_lfo1PulseWidth: ParameterModel<number>;
  modAmount_LFO5_lfo1Rate: ParameterModel<number>;
  modAmount_LFO5_lfo1Scale: ParameterModel<number>;
  modAmount_LFO5_lfo2Offset: ParameterModel<number>;
  modAmount_LFO5_lfo2Phase: ParameterModel<number>;
  modAmount_LFO5_lfo2PulseWidth: ParameterModel<number>;
  modAmount_LFO5_lfo2Rate: ParameterModel<number>;
  modAmount_LFO5_lfo2Scale: ParameterModel<number>;
  modAmount_LFO5_lfo3Offset: ParameterModel<number>;
  modAmount_LFO5_lfo3Phase: ParameterModel<number>;
  modAmount_LFO5_lfo3PulseWidth: ParameterModel<number>;
  modAmount_LFO5_lfo3Rate: ParameterModel<number>;
  modAmount_LFO5_lfo3Scale: ParameterModel<number>;
  modAmount_LFO5_lfo4Offset: ParameterModel<number>;
  modAmount_LFO5_lfo4Phase: ParameterModel<number>;
  modAmount_LFO5_lfo4PulseWidth: ParameterModel<number>;
  modAmount_LFO5_lfo4Rate: ParameterModel<number>;
  modAmount_LFO5_lfo4Scale: ParameterModel<number>;
  modAmount_LFO5_lfo5Offset: ParameterModel<number>;
  modAmount_LFO5_lfo5Phase: ParameterModel<number>;
  modAmount_LFO5_lfo5PulseWidth: ParameterModel<number>;
  modAmount_LFO5_lfo5Rate: ParameterModel<number>;
  modAmount_LFO5_lfo5Scale: ParameterModel<number>;
  modAmount_LFO5_outputGain: ParameterModel<number>;
  modAmount_LFO5_pitchOffset: ParameterModel<number>;
  outputGain: ParameterModel<number>;
  pitchOffset: ParameterModel<number>;
};
        
export const PARAMETER_IDS = [
  "delayFeedback",
  "delayTime",
  "effectOrder",
  "filterHighGain",
  "filterLowGain",
  "filterMidGain",
  "latentsOffset",
  "latentsScale",
  "lfo1BeatSync",
  "lfo1BeatSyncRate",
  "lfo1Enabled",
  "lfo1Offset",
  "lfo1Phase",
  "lfo1PulseWidth",
  "lfo1Rate",
  "lfo1Scale",
  "lfo1Type",
  "lfo2BeatSync",
  "lfo2BeatSyncRate",
  "lfo2Enabled",
  "lfo2Offset",
  "lfo2Phase",
  "lfo2PulseWidth",
  "lfo2Rate",
  "lfo2Scale",
  "lfo2Type",
  "lfo3BeatSync",
  "lfo3BeatSyncRate",
  "lfo3Enabled",
  "lfo3Offset",
  "lfo3Phase",
  "lfo3PulseWidth",
  "lfo3Rate",
  "lfo3Scale",
  "lfo3Type",
  "lfo4BeatSync",
  "lfo4BeatSyncRate",
  "lfo4Enabled",
  "lfo4Offset",
  "lfo4Phase",
  "lfo4PulseWidth",
  "lfo4Rate",
  "lfo4Scale",
  "lfo4Type",
  "lfo5BeatSync",
  "lfo5BeatSyncRate",
  "lfo5Enabled",
  "lfo5Offset",
  "lfo5Phase",
  "lfo5PulseWidth",
  "lfo5Rate",
  "lfo5Scale",
  "lfo5Type",
  "modAmount_LFO1_delayFeedback",
  "modAmount_LFO1_delayTime",
  "modAmount_LFO1_filterHighGain",
  "modAmount_LFO1_filterLowGain",
  "modAmount_LFO1_filterMidGain",
  "modAmount_LFO1_latentsOffset",
  "modAmount_LFO1_latentsScale",
  "modAmount_LFO1_lfo1Offset",
  "modAmount_LFO1_lfo1Phase",
  "modAmount_LFO1_lfo1PulseWidth",
  "modAmount_LFO1_lfo1Rate",
  "modAmount_LFO1_lfo1Scale",
  "modAmount_LFO1_lfo2Offset",
  "modAmount_LFO1_lfo2Phase",
  "modAmount_LFO1_lfo2PulseWidth",
  "modAmount_LFO1_lfo2Rate",
  "modAmount_LFO1_lfo2Scale",
  "modAmount_LFO1_lfo3Offset",
  "modAmount_LFO1_lfo3Phase",
  "modAmount_LFO1_lfo3PulseWidth",
  "modAmount_LFO1_lfo3Rate",
  "modAmount_LFO1_lfo3Scale",
  "modAmount_LFO1_lfo4Offset",
  "modAmount_LFO1_lfo4Phase",
  "modAmount_LFO1_lfo4PulseWidth",
  "modAmount_LFO1_lfo4Rate",
  "modAmount_LFO1_lfo4Scale",
  "modAmount_LFO1_lfo5Offset",
  "modAmount_LFO1_lfo5Phase",
  "modAmount_LFO1_lfo5PulseWidth",
  "modAmount_LFO1_lfo5Rate",
  "modAmount_LFO1_lfo5Scale",
  "modAmount_LFO1_outputGain",
  "modAmount_LFO1_pitchOffset",
  "modAmount_LFO2_delayFeedback",
  "modAmount_LFO2_delayTime",
  "modAmount_LFO2_filterHighGain",
  "modAmount_LFO2_filterLowGain",
  "modAmount_LFO2_filterMidGain",
  "modAmount_LFO2_latentsOffset",
  "modAmount_LFO2_latentsScale",
  "modAmount_LFO2_lfo1Offset",
  "modAmount_LFO2_lfo1Phase",
  "modAmount_LFO2_lfo1PulseWidth",
  "modAmount_LFO2_lfo1Rate",
  "modAmount_LFO2_lfo1Scale",
  "modAmount_LFO2_lfo2Offset",
  "modAmount_LFO2_lfo2Phase",
  "modAmount_LFO2_lfo2PulseWidth",
  "modAmount_LFO2_lfo2Rate",
  "modAmount_LFO2_lfo2Scale",
  "modAmount_LFO2_lfo3Offset",
  "modAmount_LFO2_lfo3Phase",
  "modAmount_LFO2_lfo3PulseWidth",
  "modAmount_LFO2_lfo3Rate",
  "modAmount_LFO2_lfo3Scale",
  "modAmount_LFO2_lfo4Offset",
  "modAmount_LFO2_lfo4Phase",
  "modAmount_LFO2_lfo4PulseWidth",
  "modAmount_LFO2_lfo4Rate",
  "modAmount_LFO2_lfo4Scale",
  "modAmount_LFO2_lfo5Offset",
  "modAmount_LFO2_lfo5Phase",
  "modAmount_LFO2_lfo5PulseWidth",
  "modAmount_LFO2_lfo5Rate",
  "modAmount_LFO2_lfo5Scale",
  "modAmount_LFO2_outputGain",
  "modAmount_LFO2_pitchOffset",
  "modAmount_LFO3_delayFeedback",
  "modAmount_LFO3_delayTime",
  "modAmount_LFO3_filterHighGain",
  "modAmount_LFO3_filterLowGain",
  "modAmount_LFO3_filterMidGain",
  "modAmount_LFO3_latentsOffset",
  "modAmount_LFO3_latentsScale",
  "modAmount_LFO3_lfo1Offset",
  "modAmount_LFO3_lfo1Phase",
  "modAmount_LFO3_lfo1PulseWidth",
  "modAmount_LFO3_lfo1Rate",
  "modAmount_LFO3_lfo1Scale",
  "modAmount_LFO3_lfo2Offset",
  "modAmount_LFO3_lfo2Phase",
  "modAmount_LFO3_lfo2PulseWidth",
  "modAmount_LFO3_lfo2Rate",
  "modAmount_LFO3_lfo2Scale",
  "modAmount_LFO3_lfo3Offset",
  "modAmount_LFO3_lfo3Phase",
  "modAmount_LFO3_lfo3PulseWidth",
  "modAmount_LFO3_lfo3Rate",
  "modAmount_LFO3_lfo3Scale",
  "modAmount_LFO3_lfo4Offset",
  "modAmount_LFO3_lfo4Phase",
  "modAmount_LFO3_lfo4PulseWidth",
  "modAmount_LFO3_lfo4Rate",
  "modAmount_LFO3_lfo4Scale",
  "modAmount_LFO3_lfo5Offset",
  "modAmount_LFO3_lfo5Phase",
  "modAmount_LFO3_lfo5PulseWidth",
  "modAmount_LFO3_lfo5Rate",
  "modAmount_LFO3_lfo5Scale",
  "modAmount_LFO3_outputGain",
  "modAmount_LFO3_pitchOffset",
  "modAmount_LFO4_delayFeedback",
  "modAmount_LFO4_delayTime",
  "modAmount_LFO4_filterHighGain",
  "modAmount_LFO4_filterLowGain",
  "modAmount_LFO4_filterMidGain",
  "modAmount_LFO4_latentsOffset",
  "modAmount_LFO4_latentsScale",
  "modAmount_LFO4_lfo1Offset",
  "modAmount_LFO4_lfo1Phase",
  "modAmount_LFO4_lfo1PulseWidth",
  "modAmount_LFO4_lfo1Rate",
  "modAmount_LFO4_lfo1Scale",
  "modAmount_LFO4_lfo2Offset",
  "modAmount_LFO4_lfo2Phase",
  "modAmount_LFO4_lfo2PulseWidth",
  "modAmount_LFO4_lfo2Rate",
  "modAmount_LFO4_lfo2Scale",
  "modAmount_LFO4_lfo3Offset",
  "modAmount_LFO4_lfo3Phase",
  "modAmount_LFO4_lfo3PulseWidth",
  "modAmount_LFO4_lfo3Rate",
  "modAmount_LFO4_lfo3Scale",
  "modAmount_LFO4_lfo4Offset",
  "modAmount_LFO4_lfo4Phase",
  "modAmount_LFO4_lfo4PulseWidth",
  "modAmount_LFO4_lfo4Rate",
  "modAmount_LFO4_lfo4Scale",
  "modAmount_LFO4_lfo5Offset",
  "modAmount_LFO4_lfo5Phase",
  "modAmount_LFO4_lfo5PulseWidth",
  "modAmount_LFO4_lfo5Rate",
  "modAmount_LFO4_lfo5Scale",
  "modAmount_LFO4_outputGain",
  "modAmount_LFO4_pitchOffset",
  "modAmount_LFO5_delayFeedback",
  "modAmount_LFO5_delayTime",
  "modAmount_LFO5_filterHighGain",
  "modAmount_LFO5_filterLowGain",
  "modAmount_LFO5_filterMidGain",
  "modAmount_LFO5_latentsOffset",
  "modAmount_LFO5_latentsScale",
  "modAmount_LFO5_lfo1Offset",
  "modAmount_LFO5_lfo1Phase",
  "modAmount_LFO5_lfo1PulseWidth",
  "modAmount_LFO5_lfo1Rate",
  "modAmount_LFO5_lfo1Scale",
  "modAmount_LFO5_lfo2Offset",
  "modAmount_LFO5_lfo2Phase",
  "modAmount_LFO5_lfo2PulseWidth",
  "modAmount_LFO5_lfo2Rate",
  "modAmount_LFO5_lfo2Scale",
  "modAmount_LFO5_lfo3Offset",
  "modAmount_LFO5_lfo3Phase",
  "modAmount_LFO5_lfo3PulseWidth",
  "modAmount_LFO5_lfo3Rate",
  "modAmount_LFO5_lfo3Scale",
  "modAmount_LFO5_lfo4Offset",
  "modAmount_LFO5_lfo4Phase",
  "modAmount_LFO5_lfo4PulseWidth",
  "modAmount_LFO5_lfo4Rate",
  "modAmount_LFO5_lfo4Scale",
  "modAmount_LFO5_lfo5Offset",
  "modAmount_LFO5_lfo5Phase",
  "modAmount_LFO5_lfo5PulseWidth",
  "modAmount_LFO5_lfo5Rate",
  "modAmount_LFO5_lfo5Scale",
  "modAmount_LFO5_outputGain",
  "modAmount_LFO5_pitchOffset",
  "outputGain",
  "pitchOffset",
];
